---
- include_vars: group_vars/{{ ansible_architecture }}.yml
  tags: ['custom', 'update']

- name: Ensure kalite is stopped if service exist
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py stop
  tags:
    - custom
  ignore_errors: yes

- name: Wait for the service Kalite to be completly stopped
  wait_for: port=8008 state=stopped timeout=120
  tags:
    - custom

- name: Create a working dir Kalite
  file: path=/home/{{ username }}/.kalite state=directory
  tags:
    - custom

- name: Uninstall previous Ka-lite version
  pip: name=ka-lite
    state=absent
  when: ansible_local.installed_software.software.kalite | version_compare('0.16.9', '<')
  tags:
    - update

- name: Install Ka-lite
  pip: name=ka-lite
    version={{ ansible_local.device_list[generic_project_name].kalite.version }}
    chdir=/home/{{ username }}/.kalite
    virtualenv_command=/usr/local/bin/virtualenv
    virtualenv=/home/{{ username }}/.kalite/env
    extra_args="--no-cache-dir"
  register: kalite_installation 
  tags: ['custom', 'update']

- name: Give rights to ideascube 
  file: path=/home/{{ username }}/.kalite state=directory
    owner={{ username }} group={{ username }} recurse=yes
  tags: ['custom', 'update']

- name: Create a user admin for kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage setup --username=admin --password=admin --noinput
  tags:
    - custom

- name: Include task nedeed when using an external hard drive
  include: ext_hdd.yml
  when: (ansible_architecture == "armhf" or ansible_architecture == "armv7l")
    and ansible_devices.sda.partitions.sda1 is defined
  tags:
    - custom

- name: Copy nginx vhost
  template: src=kalite.vhost.j2 dest=/etc/nginx/sites-available/kalite
  tags:
    - custom

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kalite dest=/etc/nginx/sites-enabled/kalite state=link
  notify: restart nginx
  tags:
    - custom

- name: Remove old sysvinit startup script
  file: path=/etc/init.d/kalite state=absent
  tags:
    - update

- name: Setup startup file
  copy: src=kalite.service dest=/etc/systemd/system/kalite.service
  tags: ['custom', 'update']

- name: Enable service kalite
  service: name=kalite enabled=yes
  tags: ['custom', 'update']

- name: Generate a zone for kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage generate_zone
  ignore_errors: yes
  tags:
    - custom

- name: Import Kalite videos if we are at BSF
  include: import_videos.yml
  when: ansible_default_ipv4.gateway == "{{ bsf_gateway }}"
  tags: ['custom', 'kalite_import']

- name: Run kalite manage setup after upgrade
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage setup --noinput
  when: kalite_installation.changed == True
  tags:
    - update

- name: Download Kalite language pack
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage retrievecontentpack download {{ item }}
  with_items: "{{ ansible_local.device_list[generic_project_name].kalite.language }}"
  when: kalite_installation.changed == True
  tags: ['custom', 'update']

- name: Start Kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py start 
  ignore_errors: yes
  tags:
    - custom

- name: Restart Kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py restart 
  ignore_errors: yes
  when: kalite_installation.changed == True
  tags:
    - update

- name: Perfom a video scan on the device
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage videoscan
  async: 1800
  poll: 0
  when: kalite_installation.changed == True
  tags: ['custom', 'update']

- name: Get ka-lite version
  shell: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py --version ; echo
  register: kalite_newversion
  tags: ['custom', 'update']

- set_fact: kalite_version="{{ kalite_newversion.stdout }}"
  tags: ['custom', 'update']

- debug: msg="kalite {{ kalite_version }} is now the current version."
  tags: ['custom', 'update']
