---
- hosts: localhost
# - hosts: SystemPushInstall

  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','package_management','kalite_import' ]

  roles:
    - set_custom_fact
    - aflatoun

  post_tasks:
    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','package_management','kalite_import' ]
