---
- name: Install conntrack
  apt: name=conntrack state=latest
  
- name: Copy captive portal script to /var/www/captiveportal
  template:
    src: cap.py.j2
    dest: /var/www/captiveportal/cap.py
    owner: ideascube
    group: ideascube
    mode: 0755

- name: Add nginx specific configuration file
  copy:
    src: nginx-captiveportal
    dest: /etc/nginx/sites-available/captiveportal
    owner: root
    group: root
    mode: 0644

- name: Enable captive portal vhost
  file: src=/etc/nginx/sites-available/captiveportal dest=/etc/nginx/sites-enabled/captiveportal state=link
  notify: restart nginx

- name: Copy captive portal public key
  copy: 
    src: ideascube.crt
    dest: /etc/nginx/ssl/ideascube.crt
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy captive portal private key
  copy:
    src: ideascube.key
    dest: /etc/nginx/ssl/ideascube.key
    owner: root
    group: root
    mode: 0640
  notify: restart nginx

- name: Add UWSGI specific configuration file
  copy:
    src: captive.ini
    dest: /etc/uwsgi/apps-available/captive.ini
    owner: root
    group: root
    mode: 0644

- name: Enable captive.ini for UWSGI
  file: src=/etc/uwsgi/apps-available/captive.ini dest=/etc/uwsgi/apps-enabled/captive.ini state=link
  notify: restart uwsgi


- name: Copy clear_iptables.sh to /usr/bin/local
  copy:
    src: clean_iptables.sh
    dest: /usr/local/bin/clean_iptables.sh
    owner: root
    group: root
    mode: 0755

- name: Add a cron entry to clean iptables rules
  cron:
    name: "Clear dead connections from CAPTIVE_PASSLIST"
    minute: */5
    job: "/usr/local/bin/clean_iptables.sh"
    state: present
  tags: ['custom', 'update']

- name: Authorize www-data to add new IPs to CAPTIVE_PASSLIST
  lineinfile:
    dest: /etc/sudoers
    line: 'www-data ALL = NOPASSWD: /sbin/iptables -I CAPTIVE_PASSLIST 1 -s * -j ACCEPT'
