---
- include_vars: group_vars/{{ ansible_architecture }}.yml
  tags: ['master','update']

- name: Copying kiwix binaries
  get_url: url={{filer_bsf}}/kiwix-serve-{{ ansible_architecture }} dest=/usr/local/bin/kiwix-serve mode=755 timeout=30
  tags:
    - master

- name: Create a kiwix directory in ideascube folder
  file: path={{zim_path}}/ owner={{username}} group={{username}} state=directory
  tags:
    - master

- name: Setup startup file
  template: src=kiwix-server.service.j2 dest=/etc/systemd/system/kiwix-server.service
  tags: ['master','update']

- name: Remove nginx configuration otherwise, if hostname var change it won't be overrided
  file: path=/etc/nginx/sites-available/kiwix state=absent
  tags:
    - custom

- name: Copy nginx vhost
  template: src=nginx.vhost.j2 dest=/etc/nginx/sites-available/kiwix
  tags: ['master','custom','update']

- name: Ensure that Ideascube cache folder belong to ideascube user 
  file: path=/var/cache/ideascube/catalog/ 
    owner={{ username }} group={{ username }} state=directory recurse=yes
  tags: 
    - update

- name: Install Kiwix catalogs
  become: yes
  become_user: ideascube
  command: ideascube catalog remotes add "{{ item.name }}" "{{ item.description }}" "{{ item.url }}"
  with_items:
  - name: "Kiwix"
    description: "Kiwix ZIM content"
    url: http://catalog.ideascube.org/kiwix.yml
  - name: "StaticSites"
    description: "Static sites"
    url: http://catalog.ideascube.org/static-sites.yml
  - name: "OSMybon"
    description: "Experimental OSM Maps catalog"
    url: http://catalog.yohanboniface.me/catalog.yml
  tags: ['master','custom','update']

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kiwix dest=/etc/nginx/sites-enabled/kiwix state=link
  notify: restart nginx
  tags: ['master','update']

- name: Enable service kiwix
  service: name=kiwix-server enabled=yes
  notify: restart kiwix
  tags: ['master','update']

- shell: ls /etc/rc5.d/S*wikipedia ; echo
  register: file_exist
  tags:
    - update

- stat: path={{file_exist.stdout}}
  register: st
  tags:
    - update

- include: dust-removal.yml
  when: st.stat.exists == True
  tags:
    - update

- name: Checkout installed.yml file size 
  stat: path=/var/ideascube/main/catalog/installed.yml
  register: installed_zim
  tags:
    - update

- include: update_catalog.yml
  when: installed_zim.stat.size is undefined
    or installed_zim.stat.size < 5