---
- name: Unblock wlan
  command: rfkill unblock wlan
  when: ansible_architecture == 'x86_64'
  ignore_errors: yes
  tags: 
    - master

- name: Check if hostapd is already installed
  shell: "dpkg -l | grep hostapd"
  ignore_errors: yes
  register: dpkg_hostapd
  tags: 
    - master

- name: Install hostapd
  apt: name=hostapd state=latest
  when: dpkg_hostapd.stdout == ""
  tags: 
    - master

- name: Remove sysVinit startup file
  file: path=/etc/init.d/hostapd state=absent
  tags: ['master', 'update']

- include_vars: group_vars/{{ ansible_architecture }}.yml
  tags: ['master', 'custom']

- name: Copy hostapd.conf file
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf owner=root group=root mode=755 backup=yes
  tags: ['master', 'custom','rename']

- name: Copy startup script
  copy: src=hostapd dest=/etc/systemd/system/hostapd.service owner=root group=root mode=664 remote_src=true
  tags: 
    - master

- name: Enable service hostapd
  service: name=hostapd enabled=yes
  tags: 
    - master
    
- name: Start hostapd
  service: name=hostapd state=started
  tags: 
    - custom
